spring:
  application:
    name: filter-service
  data:
    mongodb:
      database: filterdb-t1
      uri: mongodb://192.168.1.102:27017
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true
server:
  port: 0